In [ ]:
# ライブラリのインストール
!pip install scikit-image
!pip install saliency

In [45]:
# ライブラリのインポート
import base64
import saliency
import tensorflow as tf
import cv2

In [14]:
imported = tf.saved_model.load('saved_model')

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


In [17]:
predict = imported.signatures["serving_default"]

In [52]:
key = tf.constant(u'default')
key = tf.reshape(key, (1,1))

<tf.Tensor: shape=(1, 1), dtype=string, numpy=array([[b'default']], dtype=object)>

In [65]:
# 画像データを読み込み
with open('saliency/0.jpg', 'rb') as f:
    data = f.read()
image_bytes = tf.constant(data)
image_bytes = tf.reshape(image_bytes, (1))

In [71]:
predict(key=key, image_bytes=image_bytes)

{'labels': <tf.Tensor: shape=(1, 2), dtype=string, numpy=array([[b'other', b'death']], dtype=object)>,
 'scores': <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.05500007, 0.9449999 ]], dtype=float32)>,
 'key': <tf.Tensor: shape=(), dtype=string, numpy=b'default'>}